import type { Language } from "..";

const en: Language = {
    website: {
        header: {
            home: "Home",
            virtualServers: "Virtual Servers",
            dedicatedServers: "Dedicated Servers",
            dashboard: "Dashboard",
            login: "Login",
        },
        footer: {
            products: {
                title: "Products",
                virtualServers: "Virtual Servers",
                dedicatedServers: "Dedicated Servers",
            },
            support: {
                title: "Support",
                supportTickets: "Support Tickets",
                apiDocumentation: "API Documentation",
                documentation: "Documentation",
            },
            company: {
                title: "Company",
                privacyPolicy: "Privacy Policy",
                termsOfService: "Terms of Service",
                reportAbuse: "Report Abuse",
            },
            about: {
                title: "About DutchIS",
                description: "DutchIS aims to offer premium server hosting with great features like an extensive API and high availability.",
                vat: "VAT",
            },
            socials: "Socials",
            copyright: "Copyright",
            allRightsReserved: "All rights reserved",
        },
        home: {
            header: {
                "line1": 'Instant',
                "line2": 'Infrastructure',
                "tagline": "We're creating the best experience for you and your users from a simple VM to large networks providing services to thousands of users.",
                "callToAction": "Get Started Today!"
            },
            stats: {
                uptime: "Uptime in the last 30 days",
                happyCustomers: "Happy Customers",
                awesome: "Awesome"
            },
            flexibleVirtualServers: {
                title: "Flexible Virtual Servers",
                description: "We offer a range of virtual server solutions ideal any project. Whether you need high single core performance or lots of storage, we have you covered. Each virtual server comes with a unmetered internet connection, DDoS protection and a 99.9% uptime SLA. All to make sure that your project is performing and always online.",
                startingAt: "Starting At",
                hour: "hour",
                seePricing: "See Pricing",
                month: "mo",
                imgAlt: "Virtual server dashboard"
            },
            ourOwnInfrastructure: {
                title: "Our own Infrastructure ",
                description: "We own and operate our own infrastructure, from the servers to the network. This allows us to provide the best possible performance and experience for our customers. Our enthusiastic team is always working on improving our infrastructure and services to ensure that we can provide the best possible experience for our customers. ",
                imgAltTwoServers: "Two servers on a data center floor",
                imgAltServerRack: "Back side of DutchIS' server rack",
            },
            seeWhatYouCanSave: {
                title: "See what you can save",
                description: "Save up to 70% per month depending on the provider. No suprises at the end of the month with our predicable pricing.",
                month: "mo",
                bandwidth: "bandwidth",
                unmetered: "unmetered",
                with: "with",
                without: "without",
                pricingDisclaimer: "Pricing as of 30-06-2023. 2 vCPU, 4GB RAM and 80GB storage virtual machine. ",
                fairUseDisclaimer: "*Under fair use. See terms of service for more information",
            },
            runningCarbonGray: {
                title: "Running carbon gray with 100% Dutch wind!",
                description: "At DutchIS, we are dedicated to sustainability and use green energy to power all of our services. Our datacenter, Serverius, uses green energy certificates generated by wind turbines in the Netherlands to ensure that the electricity we use meets strict sustainability requirements. The SMK guarantee ensures that our electricity is 100% from Dutch wind turbines, so you can be confident in the environmental impact of our services. Together, we are working towards a cleaner and more sustainable future. ",
                imgAlt: "A green field with windmills in the background.",
            },
            featureBlocks: {
                designedInHouse: {
                    title: "Designed in House",
                    description: "We design and make our own hardware and software to ensure that we can provide the best possible performance and experience for our customers. ",
                },
                fullyRedundant: {
                    title: "Fully Redundant",
                    description: "We have a fully redundant network, power and cooling system to ensure that your services are always online. ",
                },
                qualitySupport: {
                    title: "Quality Support",
                    description: "You're covered by a Support Team that's renowned for being one of the most knowledgeable, friendly, and professional. Real people are ready to assist you with any issue, any time. ",
                },
                instantDeployment: {
                    title: "Instant Deployment",
                    description: "When ordering a server, your server will be instantly deployed and ready to use within seconds. No waiting for hours or days on your server! ",
                }
            }
        },
        virtualServers: {
            header: {
                title: "Virtual Servers",
                tagline: "Powerful virtual server deployed in minutes trough our custom designed dashboard or with our API. Starting at just €0,0047/hour.",
                callToAction: "Get started today!",
            },
            dashboardOverview: {
                title: "Simple yet Powerful Control",
                description: "Control your virtual server from a powerful dashboard where you have fine control with all the features you'd expect. ",
                overview: "Overview",
                overviewAlt: "The overview page of a virtual server",
                console: "Console",
                consoleAlt: "The console of a virtual server",
                settings: "Settings",
                settingsAlt: "The settings page of the dashboard",
            },
            plans: {
                title: "Virtual Server Plans",
                standard: "Standard",
                performance: "Performance",
                month: "month",
                startingAt: "Starting At",
                storage: "storage",
                networkSpeed: "network speed",
                ddosProtectionIncluded: "DDoS protection included",
                orderNow: "Order Now",
                descriptions: {
                    standard: "Our standard virtual servers run on AMD Epyc MILAN CPUs which clock to 3.7GHz. These servers are perfect for running general purpose applications like websites, databases and more. ",
                    performance: "Our performance virtual servers runs on high performance AMD Ryzen 5950x CPUs which clock to 4.9GHz. These servers are perfect for running high performance applications like game servers. ",
                },
            },
            speedIX: {
                title: "Additional SpeedIX Connection",
                description: "When running BGP on your server, you can request an extra SpeedIX peering connection in addition to your existing uplink. Besides peering with others you can order an additional Layer 2 VLAN to other data centers.",
                disclaimer: "You must have at least one IPv4 /24 associated with your ASN. ",
                imgAlt: "The SpeedIX logo",
                createATicket: "Create a Ticket",
                joinSpeedIX: "Join SpeedIX",
            },
            payPerHour: {
                title: "Pay per hour",
                description: "Stop paying for unused resources. Pay per hour and scale up or down when you need it.",
                standard: "Standard",
                performance: "Performance",
                configure: "Configure",
                storage: "Storage",
                hour: "hour",
                month: "month",
                callToAction: "Get started!",
                disclaimer: "*Monthly amount is an estimate and may vary a small amount.",
            },
            videoTutorial: {
                title: "Deployed under a minute!",
                description: "Create and deploy virtual servers under a minute with our dashboard or API. Checkout the video on the left to see how easy it is to deploy a virtual server. ",
                youtubeId: "PU4EcUH8ONg",
            },
            scaleAutomatically: {
                title: "Scale Automatically",
                description: "Why upgrade or downgrade your server manually when you can do it automatically? Our API allows you to scale your server up or down in just one API call. ",
                visitDocumentation: "Visit the API documentation",
            }
        },
        dedicatedServers: {
            header: {
                title: "Dedicated Servers",
                tagline: "Bare metal performance with our dedicated servers. Starting from 119,99 per month.",
                callToAction: "Get Started Today!",
            },
            immediate: "Immediate",
            deliveryTime: "Delivery Time",
            monthly: "Monthly",
            hours: "Hours",
            imageOfThe: "Image of the",            
            uplinkDisclaimer: "*Uplink under fair use. See terms of service for more information.",
            customConfigurations: {
                title: "Custom Configurations",
                paragraph1: "Need specific hardware configurations? Need bulk pricing for multiple servers? Contact us and we will get back to you with a custom quote. ",
                paragraph2: "It is also possible to rent a server with a commitment for a longer period of time. This can give you a discount up to 40% on the monthly price. Contact us for more information. ",
                createATicket: "Create a Ticket",
                emailUs: "Email Us",
                imgAltTwoServers: "Two servers on a data center floor",
                imgAltServerRack: "Back side of DutchIS' server rack",
            },
            speedIX: {
                title: "Additional SpeedIX Connection",
                description: "When running BGP on your server, you can request an extra SpeedIX peering connection in addition to your existing uplink. Besides peering with others you can order an additional Layer 2 VLAN to other data centers.",
                disclaimer: "You must have at least one IPv4 /24 associated with your ASN. ",
                imgAlt: "The SpeedIX logo",
                createATicket: "Create a Ticket",
                joinSpeedIX: "Join SpeedIX",
            }
        },
        termsOfService: {
            title: "Terms of Service",
            description: "Our terms of service."
        },
        privacyPolicy: {
            title: "Privacy Policy",
            description: "Our privacy policy."
        }
    }
}

export default en;
